# Generated by Django 5.1.5 on 2025-01-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_add_stay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='stay_duration',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(max_length=255),
        ),
    ]
