# Generated by Django 5.1.5 on 2025-01-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_ticket_stay_duration_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS update_ticket_stay_duration;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS update_ticket_stay_duration_insert;",
            reverse_sql=""
        ),
    ]
