# Generated by Django 5.1.5 on 2025-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_remove_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='stay_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
