# Generated by Django 5.1.5 on 2025-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_ticket_stay_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
